@localhost = http://localhost:8080
@prod = https://acc.api.katlegomodupi.com
@azure = app-acc-laptime-tracker-api.azurewebsites.net

### Get paginated sessions - Localhost
GET {{localhost}}/api/sessions?limit=10&offset=0
Accept: application/json

###

### Get paginated sessions - Azure
GET {{azure}}/api/sessions?limit=10&offset=0
Accept: application/json

###

### Get paginated sessions - Prod
GET {{prod}}/api/sessions?limit=10&offset=0
Accept: application/json


